apiVersion: v1
kind: ConfigMap
metadata:
  name: ares-config
  namespace: ares
data:
  ldap-urls: "ldap://ldap.example.com:389"
  ldap-base: "dc=example,dc=com"
  ad-domain: "example.com"
  ad-url: "ldap://ad.example.com:389"

